version: "3"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
  consumer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: guiloga/foobar_consumer
    container_name: foobar_consumer
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - rabbitmq
  test:
    image: guiloga/foobar_consumer
    command: /bin/sh -c "while ! nc -z rabbitmq:15672; do sleep 1; done; sleep 5; python -m pytest"
    container_name: guirpc_test
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - rabbitmq
    depends_on:
      - consumer
  static_analysis:
    image: guiloga/foobar_consumer
    command: python -m flake8 --max-complexity 10 --ignore E501
    container_name: guirpc_sty
    environment:
      - PYTHONUNBUFFERED=1
